languague: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t oscarsidebo/docker-test -f Dockerfile.dev .

script: 
  - docker run -e CI=true oscarsidebo/docker-test npm run test -- --coverage

