name: Docker workflow
on: 
  push: 
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build -t oscarsidebo/docker-test -f Dockerfile.dev .

      - name: Run test suite
        run: docker run -e CI=true oscarsidebo/docker-test npm run test -- --coverage
  
